### ISSUE TITLE
Proxy error:

### ISSUE THREAD

**Issue by Loukai2011** [hezhongfeng/im-fe-client#14]
Proxy error: Could not proxy request /api/v1/signup from localhost:3000 to http://127.0.0.1:7001.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
代理失败 怎么解决大佬

**Comment by hezhongfeng** [comment]
你是不是没启动后端服务啊？另外加我QQ的是你吗，最好在github这里交流

**Comment by Loukai2011** [comment]
是我

**Comment by Loukai2011** [comment]
我以为是 直接请求你的服务器呢？

**Comment by Loukai2011** [comment]
方便的话 大佬给个后端的代码库 地址吧  我clone一下 本地 起一下服务

**Comment by hezhongfeng** [comment]
那不是，你可以研究下我的另外的一个项目，这俩配套使用
https://github.com/hezhongfeng/im-server

**Comment by hezhongfeng** [comment]
需要注意数据库，自己看下

**Comment by Loukai2011** [comment]
好的 感谢大佬

**Comment by Loukai2011** [comment]
大佬 后端项目跑不起来  执行npm run start 报错

**Comment by hezhongfeng** [comment]
你需要自己学会看一些错误，加油
